# Display & Power
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_DISPLAY=y
CONFIG_I2C=y
CONFIG_SSD1306=y

# Select nice!oled display driver mode
CONFIG_NICE_OLED_ON=y
CONFIG_NICE_EPAPER_ON=n
CONFIG_NICE_CUSTOM_ON=n

# LVGL 9 Stability Fixes (Notaduck)
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=8192
CONFIG_HW_STACK_PROTECTION=y